// data.js
const data = [
  {
    "id": 123,
    "image": "teokbokki.png",
    "title": "Tteokbokki: 떡볶이",
    "slug": "tteokbokki",
    "category": "Korean",
    "ingredients": [
        "Tteok (Rice Cakes): 200-300 grams",
        "Fish Cake: 2-3 sheets (cut into bite-sized pieces)",
        "Onion: Half (sliced thinly)",
        "Green Onion: 2 stalks (cut into short pieces)",
        "Gochujang (Korean Chili Paste): 2-3 tablespoons (adjust for desired spiciness)",
        "Gochugaru (Korean Chili Flakes): 1-2 teaspoons (for extra heat)",
        "Sugar: 1-2 tablespoons",
        "Soy Sauce: 1-2 teaspoons",
        "Sesame Oil: 1 teaspoon (for fragrance)",
        "Water/Anchovy Broth: 1-2 cups",
        "Toasted Sesame Seeds: For garnish"
    ],
    "steps": [
        "Rinse the tteok. If it’s too hard, soak it in warm water for 10-15 minutes.",
        "Cut the fish cakes, onion, and green onions into the desired sizes.",
        "In a pan, bring water or anchovy broth (for extra flavor) to a boil.",
        "Add gochujang, gochugaru, sugar, and soy sauce to the broth. Stir until well combined.",
        "Add the tteok and fish cakes into the sauce. Cook over medium heat, stirring occasionally to prevent sticking.",
        "Add the onion and green onions. Simmer for another 5-7 minutes until the sauce thickens and the tteok becomes soft.",
        "Turn off the heat, drizzle sesame oil, and mix well.",
        "Serve on a plate, garnished with toasted sesame seeds."
    ]
  },
  //Japanese Cruisene
  {
    id: 1,
    image: "ramen.png",
    title: "Ramen: ラーメン",
    slug: "ramen",
    category: "Japanese",
    ingredients: [
      "Ramen Noodles: 200-300 grams",
      "Chicken Broth: 4 cups",
      "Soy Sauce: 2 tablespoons",
      "Miso Paste: 1 tablespoon",
      "Garlic: 2 cloves (minced)",
      "Ginger: 1 teaspoon (grated)",
      "Boiled Egg: 1-2 (halved)",
      "Green Onion: 2 stalks (sliced)",
      "Corn: 1/4 cup",
      "Seaweed (Nori): For garnish",
      "Sesame Oil: 1 teaspoon",
      "Pork Belly (Chashu): Optional, 2-3 slices",
    ],
    steps: [
      "Cook the ramen noodles according to the package instructions. Drain and set aside.",
      "In a pot, heat sesame oil and sauté garlic and ginger until fragrant.",
      "Add chicken broth, soy sauce, and miso paste. Stir well and let it simmer for 5-10 minutes.",
      "Prepare the toppings: slice boiled eggs, green onions, and pork belly if using.",
      "In a bowl, add the cooked noodles and pour the hot broth over them.",
      "Top with boiled egg halves, sliced green onions, corn, seaweed, and pork belly.",
      "Serve immediately and enjoy your delicious ramen!",
    ],
  },
  {
    id: 2,
    image: "zaru soba.png",
    title: "Zaru Soba",
    slug: "zarusoba",
    category: "Japanese",
    ingredients: [
      "Soba Noodles: 200 grams",
      "Soy Sauce: 3 tablespoons",
      "Dashi Stock: 1/2 cup",
      "Mirin: 1 tablespoon",
      "Wasabi: To taste",
      "Green Onion: 1 stalk (sliced)",
      "Seaweed (Nori): Sliced for garnish",
      "Ice Cubes: Optional, for cooling noodles",
    ],
    steps: [
      "Cook the soba noodles according to the package instructions. Rinse with cold water and set aside.",
      "Prepare the dipping sauce by mixing soy sauce, dashi stock, and mirin in a small bowl.",
      "Arrange the noodles on a plate and optionally place ice cubes to keep them cool.",
      "Serve with dipping sauce, garnished with green onions, wasabi, and nori.",
      "Dip the noodles into the sauce and enjoy!",
    ],
  },
  {
    id: 3,
    image: "Nigiri.png",
    title: "Nigiri",
    slug: "nigiri",
    category: "Japanese",
    ingredients: [
      "Sushi Rice: 2 cups (cooked and seasoned)",
      "Fresh Fish (e.g., Salmon, Tuna): 200 grams (sliced)",
      "Wasabi: To taste",
      "Soy Sauce: For serving",
    ],
    steps: [
      "Prepare the sushi rice by cooking and seasoning it with rice vinegar, sugar, and salt.",
      "Take a small amount of rice and shape it into an oval with your hands.",
      "Place a small amount of wasabi on top of the rice.",
      "Lay a slice of fish over the rice and gently press to secure.",
      "Serve with soy sauce and enjoy!",
    ],
  },
  {
    id: 4,
    image: "Tonkatsu.png",
    title: "Tonkatsu",
    slug: "tonkatsu",
    category: "Japanese",
    ingredients: [
      "Pork Cutlets: 2 pieces",
      "Flour: 1/2 cup",
      "Eggs: 2 (beaten)",
      "Panko Breadcrumbs: 1 cup",
      "Vegetable Oil: For frying",
      "Tonkatsu Sauce: For serving",
      "Shredded Cabbage: For garnish",
    ],
    steps: [
      "Season the pork cutlets with salt and pepper.",
      "Coat each cutlet in flour, dip in beaten eggs, and then coat with panko breadcrumbs.",
      "Heat vegetable oil in a frying pan and fry the cutlets until golden brown and cooked through.",
      "Place on a paper towel to drain excess oil.",
      "Serve with tonkatsu sauce and shredded cabbage.",
    ],
  },
  //Japanese Cruisene

  //Thai Cruisene
  {
    id: 5,
    image: "Tom yum goong.png",
    title: "Tom Yum Goong",
    slug: "Tomyumgoong",
    category: "Thai",
    ingredients: [
      "Shrimp: 200 grams (peeled and deveined)",
      "Lemongrass: 2 stalks (smashed)",
      "Kaffir Lime Leaves: 3-4 leaves",
      "Galangal: 3 slices",
      "Thai Chili: 2-3 (sliced)",
      "Mushrooms: 100 grams (sliced)",
      "Fish Sauce: 2 tablespoons",
      "Lime Juice: 2 tablespoons",
      "Coconut Milk: 1 cup",
      "Chicken Broth: 2 cups",
      "Coriander: For garnish",
    ],
    steps: [
      "Boil the chicken broth and add lemongrass, galangal, and kaffir lime leaves.",
      "Add shrimp and mushrooms to the boiling broth.",
      "Season with fish sauce, lime juice, and coconut milk.",
      "Add Thai chili for spice and simmer for 5 minutes.",
      "Serve hot, garnished with coriander.",
    ],
  },
  {
    id: 6,
    image: "Som tum.png",
    title: "Som Tum (Papaya Salad)",
    slug: "Somtum",
    category: "Thai",
    ingredients: [
      "Green Papaya: 1 cup (shredded)",
      "Cherry Tomatoes: 5-6 (halved)",
      "Green Beans: 4-5 (cut into pieces)",
      "Garlic: 2 cloves",
      "Thai Chili: 2-3",
      "Fish Sauce: 1 tablespoon",
      "Palm Sugar: 1 tablespoon",
      "Lime Juice: 2 tablespoons",
      "Peanuts: 2 tablespoons (roasted)",
    ],
    steps: [
      "Pound garlic and Thai chili in a mortar and pestle.",
      "Add green beans, tomatoes, and shredded papaya. Gently pound and mix.",
      "Season with fish sauce, lime juice, and palm sugar. Mix well.",
      "Top with roasted peanuts and serve fresh.",
    ],
  },
  {
    id: 7,
    image: "Pad Thai.png",
    title: "Pad Thai",
    slug: "PadThai",
    category: "Thai",
    ingredients: [
      "Rice Noodles: 200 grams",
      "Shrimp: 150 grams",
      "Eggs: 2",
      "Bean Sprouts: 1 cup",
      "Chives: 1/2 cup (chopped)",
      "Garlic: 2 cloves (minced)",
      "Fish Sauce: 2 tablespoons",
      "Tamarind Paste: 1 tablespoon",
      "Sugar: 1 tablespoon",
      "Peanuts: 2 tablespoons (crushed)",
      "Vegetable Oil: 2 tablespoons",
      "Lime: 1 (sliced for garnish)",
    ],
    steps: [
      "Soak the rice noodles in warm water until soft. Drain and set aside.",
      "Heat oil in a pan and sauté garlic until fragrant.",
      "Add shrimp and cook until pink, then push to one side of the pan.",
      "Add eggs, scramble, and mix with shrimp.",
      "Add noodles, fish sauce, tamarind paste, and sugar. Stir until well combined.",
      "Mix in bean sprouts and chives. Cook for 2 minutes.",
      "Serve with crushed peanuts and lime wedges.",
    ],
  },
  {
    id: 8,
    image: "Kao Pad.png",
    title: "Kao Pad (Fried Rice)",
    slug: "KaoPad",
    category: "Thai",
    ingredients: [
      "Cooked Rice: 2 cups (day-old rice works best)",
      "Eggs: 2",
      "Garlic: 2 cloves (minced)",
      "Vegetables: 1 cup (e.g., peas, carrots, corn)",
      "Soy Sauce: 2 tablespoons",
      "Fish Sauce: 1 tablespoon",
      "Green Onion: 1 stalk (chopped)",
      "Lime: 1 (sliced for garnish)",
      "Vegetable Oil: 2 tablespoons",
    ],
    steps: [
      "Heat oil in a pan and sauté garlic until fragrant.",
      "Add eggs and scramble them in the pan.",
      "Add rice and mix well with the eggs.",
      "Stir in vegetables, soy sauce, and fish sauce.",
      "Cook until heated through. Add green onions.",
      "Serve with lime wedges and garnish with additional green onions.",
    ],
  },
  //Thai Cruisene

  //Chinese Cuisine
  {
    id: 9,
    image: "Peking Roasted Duck.png",
    title: "Peking Roasted Duck",
    slug: "PekingRoastedDuck",
    category: "Chinese",
    ingredients: [
      "Duck: 1 whole (cleaned)",
      "Hoisin Sauce: 3 tablespoons",
      "Honey: 2 tablespoons",
      "Soy Sauce: 2 tablespoons",
      "Five-Spice Powder: 1 teaspoon",
      "Ginger: 2 slices",
      "Garlic: 2 cloves (minced)",
      "Pancakes: For serving",
      "Cucumber: 1 (sliced thinly)",
      "Green Onion: 2 stalks (sliced thinly)",
    ],
    steps: [
      "Clean and dry the duck thoroughly. Prick the skin all over with a fork.",
      "Mix hoisin sauce, honey, soy sauce, five-spice powder, ginger, and garlic to make a marinade.",
      "Rub the marinade all over the duck, including inside the cavity.",
      "Hang the duck to dry in a cool, well-ventilated area for 4-6 hours.",
      "Preheat the oven to 180°C (350°F). Roast the duck for 1.5 to 2 hours, basting occasionally.",
      "Serve with pancakes, cucumber, and green onions.",
    ],
  },
  {
    id: 10,
    image: "Kung Pao Chicken.png",
    title: "Kung Pao Chicken",
    slug: "KungPaoChicken",
    category: "Chinese",
    ingredients: [
      "Chicken Breast: 300 grams (cut into cubes)",
      "Bell Peppers: 1 cup (diced)",
      "Peanuts: 1/4 cup (roasted)",
      "Garlic: 2 cloves (minced)",
      "Ginger: 1 teaspoon (minced)",
      "Soy Sauce: 2 tablespoons",
      "Oyster Sauce: 1 tablespoon",
      "Cornstarch: 1 teaspoon (mixed with water)",
      "Dried Red Chilies: 4-5 (optional)",
      "Vegetable Oil: 2 tablespoons",
    ],
    steps: [
      "Heat oil in a pan and sauté garlic, ginger, and dried red chilies.",
      "Add chicken and cook until no longer pink.",
      "Add bell peppers and stir-fry for 2 minutes.",
      "Mix soy sauce, oyster sauce, and cornstarch slurry. Add to the pan.",
      "Cook until the sauce thickens, then stir in peanuts.",
      "Serve hot with steamed rice.",
    ],
  },
  {
    id: 11,
    image: "Sweet and Sour Pork.png",
    title: "Sweet and Sour Pork",
    slug: "SweetandSourPork",
    category: "Chinese",
    ingredients: [
      "Pork: 300 grams (cut into cubes)",
      "Bell Peppers: 1 cup (diced)",
      "Pineapple Chunks: 1/2 cup",
      "Garlic: 2 cloves (minced)",
      "Soy Sauce: 2 tablespoons",
      "Vinegar: 2 tablespoons",
      "Sugar: 2 tablespoons",
      "Ketchup: 2 tablespoons",
      "Cornstarch: 1 tablespoon (for coating)",
      "Vegetable Oil: 2 tablespoons",
    ],
    steps: [
      "Coat the pork pieces with cornstarch and fry until golden brown. Set aside.",
      "In the same pan, sauté garlic and bell peppers.",
      "Add pineapple chunks and stir-fry for 2 minutes.",
      "Mix soy sauce, vinegar, sugar, and ketchup. Pour into the pan and bring to a boil.",
      "Add the fried pork and toss to coat evenly.",
      "Serve hot with steamed rice.",
    ],
  },
  {
    id: 12,
    image: "Ma Po Tofu.png",
    title: "Ma Po Tofu",
    slug: "MaPoTofu",
    category: "Chinese",
    ingredients: [
      "Tofu: 300 grams (cubed)",
      "Ground Pork: 150 grams",
      "Garlic: 2 cloves (minced)",
      "Ginger: 1 teaspoon (minced)",
      "Doubanjiang (Spicy Bean Paste): 1 tablespoon",
      "Soy Sauce: 1 tablespoon",
      "Cornstarch: 1 teaspoon (mixed with water)",
      "Chicken Broth: 1 cup",
      "Green Onion: 1 stalk (chopped)",
      "Sesame Oil: 1 teaspoon",
    ],
    steps: [
      "Heat oil in a pan and sauté garlic, ginger, and doubanjiang.",
      "Add ground pork and cook until browned.",
      "Pour in chicken broth and bring to a boil.",
      "Add tofu and simmer for 5 minutes.",
      "Stir in soy sauce and cornstarch slurry. Cook until the sauce thickens.",
      "Drizzle sesame oil and garnish with green onions before serving.",
    ],
  },
  //Chinese Cuisine

  //Western Cuisine
  {
    id: 13,
    image: "Hamburger.png",
    title: "Hamburger",
    slug: "Hamburger",
    category: "Western",
    ingredients: [
      "Ground Beef: 300 grams",
      "Hamburger Buns: 2 pieces",
      "Lettuce: 2 leaves",
      "Tomato: 1 (sliced)",
      "Cheddar Cheese: 2 slices",
      "Onion: 1/2 (sliced)",
      "Pickles: Optional",
      "Ketchup: 2 tablespoons",
      "Mustard: 1 tablespoon",
      "Salt: To taste",
      "Black Pepper: To taste",
    ],
    steps: [
      "Season the ground beef with salt and black pepper. Form into patties.",
      "Heat a skillet or grill and cook the patties for 3-4 minutes on each side, or until cooked to your desired doneness.",
      "Toast the hamburger buns lightly on the skillet or grill.",
      "Assemble the burger by layering lettuce, patty, cheese, tomato, onion, and pickles.",
      "Top with ketchup and mustard, then close the bun.",
      "Serve immediately with fries or a side salad.",
    ],
  },
  {
    id: 14,
    image: "Chicago Deep-Dish Pizza.png",
    title: "Chicago Deep-Dish Pizza",
    slug: "ChicagoDeep-DishPizza",
    category: "Western",
    ingredients: [
      "Pizza Dough: Enough for one deep-dish crust",
      "Mozzarella Cheese: 300 grams (shredded)",
      "Italian Sausage: 200 grams (crumbled)",
      "Crushed Tomatoes: 1 can (400 grams)",
      "Parmesan Cheese: 50 grams (grated)",
      "Olive Oil: 1 tablespoon",
      "Garlic: 2 cloves (minced)",
      "Oregano: 1 teaspoon",
      "Salt: To taste",
      "Black Pepper: To taste",
    ],
    steps: [
      "Preheat the oven to 200°C (400°F).",
      "Roll out the pizza dough and press it into a deep-dish pizza pan.",
      "Layer mozzarella cheese at the bottom, followed by crumbled sausage.",
      "In a bowl, mix crushed tomatoes, garlic, oregano, salt, and pepper. Spread the mixture over the sausage.",
      "Top with grated Parmesan cheese and drizzle olive oil.",
      "Bake for 25-30 minutes, or until the crust is golden and the cheese is bubbly.",
      "Let cool for a few minutes before slicing and serving.",
    ],
  },
  {
    id: 15,
    image: "Steak.png",
    title: "Steak",
    slug: "Steak",
    category: "Western",
    ingredients: [
      "Beef Steak: 300 grams (sirloin, ribeye, or filet mignon)",
      "Salt: To taste",
      "Black Pepper: To taste",
      "Butter: 2 tablespoons",
      "Garlic: 2 cloves (smashed)",
      "Thyme: 2 sprigs",
      "Olive Oil: 1 tablespoon",
    ],
    steps: [
      "Season the steak generously with salt and black pepper on both sides.",
      "Heat olive oil in a skillet over high heat.",
      "Sear the steak for 2-3 minutes on each side to form a crust.",
      "Reduce the heat to medium, add butter, garlic, and thyme to the pan.",
      "Baste the steak with the melted butter for 2-3 minutes for medium-rare doneness.",
      "Remove the steak from the skillet and let it rest for 5 minutes before serving.",
    ],
  },
  {
    id: 16,
    image: "Apple Pie.png",
    title: "Apple Pie",
    slug: "ApplePie",
    category: "Western",
    ingredients: [
      "Apples: 4-5 (peeled, cored, and sliced)",
      "Pie Crust: Enough for a top and bottom crust",
      "Sugar: 1/2 cup",
      "Brown Sugar: 1/4 cup",
      "Cinnamon: 1 teaspoon",
      "Nutmeg: 1/4 teaspoon",
      "Cornstarch: 1 tablespoon",
      "Butter: 2 tablespoons (cubed)",
      "Egg: 1 (beaten, for egg wash)",
    ],
    steps: [
      "Preheat the oven to 180°C (350°F).",
      "Mix apples, sugar, brown sugar, cinnamon, nutmeg, and cornstarch in a bowl.",
      "Roll out the bottom pie crust and press it into a pie dish.",
      "Fill the crust with the apple mixture and dot with butter cubes.",
      "Cover with the top crust, seal the edges, and cut slits for ventilation.",
      "Brush the top with beaten egg and bake for 50-60 minutes, or until golden brown.",
      "Cool for at least 30 minutes before serving.",
    ],
  },
  //Western Cuisine

  //Clean Eating Cuisine
  {
    id: 17,
    image: "Healthy Detox Salad .png",
    title: "Healthy Detox Salad",
    slug: "HealthyDetoxSalad",
    category: "Clean Eating",
    ingredients: [
      "Mixed Greens: 2 cups",
      "Cucumber: 1 (sliced)",
      "Carrot: 1 (shredded)",
      "Avocado: 1 (sliced)",
      "Tomatoes: 1/2 cup (cherry or grape)",
      "Lemon Juice: 1 tablespoon",
      "Olive Oil: 1 tablespoon",
      "Hemp Seeds: 1 tablespoon",
      "Apple Cider Vinegar: 1 teaspoon",
      "Sea Salt: To taste",
      "Pepper: To taste",
    ],
    steps: [
      "Wash and prepare all vegetables.",
      "In a large bowl, combine mixed greens, cucumber, carrot, avocado, and tomatoes.",
      "In a small bowl, whisk together lemon juice, olive oil, apple cider vinegar, salt, and pepper.",
      "Pour the dressing over the salad and toss gently.",
      "Top with hemp seeds before serving.",
    ],
  },
  {
    id: 18,
    image: "Roasted Salmon Caprese.png",
    title: "Roasted Salmon Caprese",
    slug: "RoastedSalmonCaprese",
    category: "Clean Eating",
    ingredients: [
      "Salmon Fillet: 2 pieces",
      "Tomatoes: 1 cup (cherry or grape, halved)",
      "Fresh Mozzarella: 1/2 cup (sliced)",
      "Basil Leaves: 1/4 cup (fresh)",
      "Olive Oil: 1 tablespoon",
      "Balsamic Vinegar: 1 teaspoon",
      "Garlic: 2 cloves (minced)",
      "Salt: To taste",
      "Pepper: To taste",
    ],
    steps: [
      "Preheat oven to 200°C (400°F).",
      "Place salmon fillets on a baking sheet and drizzle with olive oil, garlic, salt, and pepper.",
      "Roast salmon for 12-15 minutes or until cooked through.",
      "While the salmon is cooking, prepare the Caprese by combining tomatoes, mozzarella, and basil leaves.",
      "Once the salmon is done, top with the Caprese mixture.",
      "Drizzle with balsamic vinegar and serve.",
    ],
  },
  {
    id: 19,
    image: "Baked Falafel Sandwiches.png",
    title: "Baked Falafel Sandwiches",
    slug: "BakedFalafelSandwiches",
    category: "Clean Eating",
    ingredients: [
      "Chickpeas: 1 can (drained and rinsed)",
      "Parsley: 1/4 cup (fresh, chopped)",
      "Cilantro: 1/4 cup (fresh, chopped)",
      "Onion: 1/4 cup (chopped)",
      "Garlic: 2 cloves (minced)",
      "Ground Cumin: 1 teaspoon",
      "Ground Coriander: 1/2 teaspoon",
      "Baking Powder: 1 teaspoon",
      "Flour: 2 tablespoons",
      "Olive Oil: 1 tablespoon (for baking)",
      "Salt: To taste",
      "Pepper: To taste",
      "Whole Wheat Pita: 2 (for sandwiches)",
      "Tahini Sauce: 2 tablespoons",
    ],
    steps: [
      "Preheat the oven to 180°C (350°F) and line a baking sheet with parchment paper.",
      "In a food processor, combine chickpeas, parsley, cilantro, onion, garlic, cumin, coriander, baking powder, flour, salt, and pepper.",
      "Pulse until the mixture comes together but still has some texture.",
      "Shape the mixture into small balls and place them on the prepared baking sheet.",
      "Drizzle with olive oil and bake for 25-30 minutes, flipping halfway through, until golden brown.",
      "Serve in pita bread with tahini sauce.",
    ],
  },
  {
    id: 20,
    image: "Chicken & Kale Soup.png",
    title: "Chicken & Kale Soup",
    slug: "ChickenKaleSoup",
    category: "Clean Eating",
    ingredients: [
      "Chicken Breast: 2 (boneless, skinless, cubed)",
      "Kale: 2 cups (chopped)",
      "Carrot: 1 (diced)",
      "Celery: 1 stalk (diced)",
      "Onion: 1 (chopped)",
      "Garlic: 2 cloves (minced)",
      "Chicken Broth: 4 cups",
      "Olive Oil: 1 tablespoon",
      "Thyme: 1 teaspoon (dried)",
      "Salt: To taste",
      "Pepper: To taste",
    ],
    steps: [
      "In a large pot, heat olive oil over medium heat.",
      "Add chicken breast and cook until browned, then set aside.",
      "In the same pot, add onion, garlic, carrot, and celery and cook for 5 minutes.",
      "Add chicken broth, thyme, salt, and pepper, and bring to a boil.",
      "Reduce the heat and simmer for 15-20 minutes until the vegetables are tender.",
      "Add the chicken back into the pot along with the kale and cook for another 5 minutes.",
      "Adjust seasoning if necessary and serve hot.",
    ],
  },
  //Clean Eating Cuisine

  //breakfast
  {
    id: 21,
    image: "Macaroni soup.png",
    title: "Macaroni soup",
    slug: "Macaronisoup",
    category: "Breakfast",
    ingredients: [
      "Macaroni: 1 cup",
      "Olive Oil: 1 tablespoon",
      "Garlic: 2 cloves (minced)",
      "Onion: 1/4 cup (diced)",
      "Carrots: 1/4 cup (diced)",
      "Celery: 1/4 cup (diced)",
      "Tomatoes: 2 (diced) or 1 cup canned tomatoes",
      "Vegetable Broth: 4 cups",
      "Milk: 1/2 cup",
      "Salt: 1/2 teaspoon (adjust to taste)",
      "Black Pepper: 1/4 teaspoon",
      "Bay Leaf: 1",
      "Parsley: 2 tablespoons (chopped, for garnish)",
    ],
    steps: [
      "Boil macaroni in salted water for 8-10 minutes until al dente. Drain and set aside.",
      "Heat olive oil in a pot over medium heat. Add garlic and onion, sauté until fragrant.",
      "Add carrots and celery, cook for 2-3 minutes.",
      "Stir in diced tomatoes and cook until softened.",
      "Pour in vegetable broth and add the bay leaf. Bring to a boil, then reduce heat and simmer for 10 minutes.",
      "Stir in milk and season with salt and black pepper.",
      "Add cooked macaroni to the soup and simmer for another 2-3 minutes.",
      "Serve hot, garnished with parsley.",
    ],
  },
  {
    id: 22,
    image: "pancakes.png",
    title: "pancakes",
    slug: "pancakes",
    category: "Breakfast",
    ingredients: [
      "All-purpose Flour: 1 cup",
      "Baking Powder: 2 teaspoons",
      "Sugar: 2 tablespoons",
      "Salt: 1/4 teaspoon",
      "Milk: 3/4 cup",
      "Egg: 1 (beaten)",
      "Unsalted Butter: 2 tablespoons (melted)",
      "Vanilla Extract: 1 teaspoon",
    ],
    steps: [
      "In a large bowl, combine flour, baking powder, sugar, and salt.",
      "In a separate bowl, whisk together milk, egg, melted butter, and vanilla extract.",
      "Pour the wet ingredients into the dry ingredients and mix until just combined. Do not overmix; the batter should be slightly lumpy.",
      "Heat a non-stick skillet or griddle over medium heat and lightly grease with butter or oil.",
      "Pour 1/4 cup of batter onto the skillet for each pancake. Cook until bubbles form on the surface and the edges look set, about 2-3 minutes.",
      "Flip the pancake and cook the other side until golden brown, about 1-2 minutes.",
      "Repeat with the remaining batter.",
      "Serve warm with maple syrup, fresh fruit, or your favorite toppings.",
    ],
  },
  {
    id: 23,
    image: "Berry Baked Porridge.png",
    title: "Berry Baked Porridge",
    slug: "BerryBakedPorridge",
    category: "Breakfast",
    ingredients: [
      "Rolled Oats: 1 cup",
      "Milk (or plant-based milk): 1 1/2 cups",
      "Egg: 1 (beaten)",
      "Honey or Maple Syrup: 2 tablespoons",
      "Vanilla Extract: 1 teaspoon",
      "Mixed Berries: 1 cup (fresh or frozen)",
      "Baking Powder: 1 teaspoon",
      "Cinnamon: 1/2 teaspoon",
      "Salt: 1/4 teaspoon",
      "Chopped Nuts (optional): 1/4 cup",
      "Butter or Coconut Oil: 1 tablespoon (melted, for greasing)",
    ],
    steps: [
      "Preheat the oven to 180°C (350°F) and lightly grease a baking dish with butter or coconut oil.",
      "In a mixing bowl, combine oats, baking powder, cinnamon, and salt.",
      "In another bowl, whisk together milk, egg, honey (or maple syrup), and vanilla extract.",
      "Pour the wet ingredients into the dry ingredients and stir to combine.",
      "Fold in the mixed berries and nuts (if using).",
      "Pour the mixture into the prepared baking dish and spread it evenly.",
      "Bake for 25-30 minutes or until the top is golden brown and the porridge is set.",
      "Let it cool slightly before serving. Serve warm with additional berries, yogurt, or a drizzle of honey.",
    ],
  },
  {
    id: 24,
    image: "Croissants.png",
    title: "Croissants",
    slug: "Croissants",
    category: "Breakfast",
    ingredients: [
      "All-purpose Flour: 3 3/4 cups",
      "Sugar: 1/4 cup",
      "Salt: 1 1/2 teaspoons",
      "Instant Yeast: 2 teaspoons",
      "Milk: 1 cup (warm)",
      "Unsalted Butter: 1 cup (cold, for laminating)",
      "Egg: 1 (beaten, for egg wash)",
      "Water: 1/4 cup (warm)",
    ],
    steps: [
      "Mix warm milk, water, sugar, and yeast. Let sit for 10 minutes until frothy.",
      "Combine flour, salt, and yeast mixture. Knead into smooth dough and let rest until doubled in size.",
      "Roll dough into a rectangle. Place flattened cold butter in the center and fold dough over it. Chill for 30 minutes.",
      "Roll, fold into thirds, and chill. Repeat 3 times.",
      "Shape into croissants, let rise for 1 hour.",
      "Brush with egg wash and bake at 200°C (400°F) for 20-25 minutes until golden brown. Cool before serving.",
    ],
  },
  //breakfast

  //Lunch
  {
    id: 25,
    image: "beef steak.png",
    title: "beef steak",
    slug: "beefsteak",
    category: "Lunch",
    ingredients: [
      "Beef Steak (e.g., Ribeye or Sirloin): 300g",
      "Salt: 1 teaspoon",
      "Black Pepper: 1 teaspoon",
      "Olive Oil: 1 tablespoon",
      "Unsalted Butter: 1 tablespoon",
      "Garlic Cloves: 2 (crushed)",
      "Fresh Rosemary: 1 sprig",
    ],
    steps: [
      "Take the steak out of the fridge and let it rest for 30 minutes to reach room temperature.",
    "Season both sides of the steak generously with salt and black pepper.",
    "Heat a skillet over high heat and add olive oil until hot.",
    "Place the steak in the skillet and sear for 2-3 minutes per side for medium-rare. Adjust time for desired doneness.",
    "Add butter, crushed garlic, and rosemary to the skillet. Baste the steak with the melted butter for 1-2 minutes.",
    "Remove the steak from the skillet and let it rest for 5 minutes before serving.",
    "Slice the steak against the grain and serve hot. Enjoy!",
    ],
  },

  {
    id: 26,
    image: "beef stew.png",
    title: "beef stew",
    slug: "beefstew",
    category: "Lunch",
    ingredients: [
      "Beef: 500g (cut into bite-sized pieces)",
      "Carrots: 2 (sliced)",
      "Potatoes: 3 (diced)",
      "Onion: 1 (chopped)",
      "Garlic: 3 cloves (minced)",
      "Tomato Paste: 2 tablespoons",
      "Flour: 2 tablespoons",
      "Beef Broth: 4 cups",
      "Olive Oil: 2 tablespoons",
      "Bay Leaf: 2",
      "Thyme: 1 teaspoon",
      "Salt: to taste",
      "Pepper: to taste",
    ],
    steps: [
      "Heat olive oil in a large pot over medium heat.",
      "Season beef with salt and pepper, coat with flour, and sear until browned. Remove and set aside.",
      "In the same pot, sauté onion and garlic until fragrant.",
      "Stir in tomato paste, then add beef broth, bay leaves, and thyme. Mix well.",
      "Return beef to the pot, cover, and simmer on low heat for 1.5 hours.",
      "Add carrots and potatoes, then simmer for another 30 minutes until vegetables are tender.",
      "Adjust seasoning with salt and pepper. Serve hot.",
    ],
  },

  {
    id: 27,
    image: "Mashed potatoes.png",
    title: "Mashed potatoes",
    slug: "Mashedpotatoes",
    category: "Lunch",
    ingredients: [
      "Potatoes: 1 kg (peeled and cut into chunks)",
      "Butter: 100g (unsalted, softened)",
      "Milk: 1/2 cup (warm)",
      "Salt: to taste",
      "Pepper: to taste",
      "Garlic (optional): 2 cloves (minced, sautéed in butter)",
      "Parsley (optional): 1 tablespoon (chopped, for garnish)",
    ],
    steps: [
      "Boil potatoes in salted water until fork-tender (15-20 minutes).",
      "Drain the potatoes and return to the pot. Let them sit for 1-2 minutes to dry.",
      "Mash the potatoes using a potato masher or ricer until smooth.",
      "Mix in butter until fully melted and incorporated.",
      "Gradually add warm milk while mixing until the desired consistency is reached.",
      "Season with salt and pepper to taste.",
      "Optional: Stir in sautéed garlic for extra flavor.",
      "Garnish with parsley before serving, if desired.",
    ],
  },

  {
    id: 28,
    image: "Omelet.png",
    title: "Omelet",
    slug: "Omelet",
    category: "Lunch",
    ingredients: [
      "Eggs: 3",
    "Milk (optional): 2 tablespoons",
    "Butter: 1 tablespoon",
    "Salt: to taste",
    "Pepper: to taste",
    "Cheese (optional): 1/4 cup (shredded)",
    "Vegetables (optional): 1/4 cup (chopped, e.g., onions, bell peppers, mushrooms)",
    "Ham or Bacon (optional): 1/4 cup (chopped)",
    ],
    steps: [
      "Crack eggs into a bowl. Add milk (if using), salt, and pepper. Whisk until well combined.",
    "Heat a non-stick pan over medium heat and melt the butter.",
    "Pour the egg mixture into the pan, tilting the pan to spread the mixture evenly.",
    "Optional: Add cheese, vegetables, or meat on one half of the omelet while the eggs are still slightly runny.",
    "Cook until the edges are set and the bottom is golden brown (2-3 minutes).",
    "Carefully fold the omelet in half using a spatula.",
    "Slide the omelet onto a plate and serve immediately.",
    ],
  },
  //Lunch

  //Dinner
  {
    id: 29,
    image: "Curry.png",
    title: "Curry",
    slug: "Curry",
    category: "Dinner",
    ingredients: [
      "Meat (Chicken, Beef, or Pork): 300 grams (cut into bite-sized pieces)",
      "Potatoes: 2 (peeled and diced)",
      "Carrots: 1 (peeled and diced)",
      "Onion: 1 (sliced)",
      "Coconut Milk: 1 cup",
      "Water: 1-2 cups",
      "Curry Powder: 2-3 tablespoons",
      "Soy Sauce: 1 tablespoon",
      "Sugar: 1 tablespoon",
      "Salt: To taste",
      "Cooking Oil: 2 tablespoons",
      "Bay Leaves: 1-2 (optional)",
      "Fresh Coriander: For garnish",
    ],
    steps: [
      "Prepare ingredients by cutting meat and vegetables into desired sizes.",
      "Heat cooking oil in a large pan. Add onions and sauté until soft.",
      "Add curry powder and stir until fragrant.",
      "Add the meat and cook until lightly browned.",
      "Add potatoes and carrots, and stir to combine.",
      "Pour in water and coconut milk. Add bay leaves if using.",
      "Simmer for 10-15 minutes or until vegetables are tender.",
      "Season with soy sauce, sugar, and salt. Adjust to taste.",
      "Serve hot, garnished with fresh coriander. Enjoy with steamed rice or bread.",
    ],
  },

  {
    id: 30,
    image: "fried basil.png",
    title: "fried basil",
    slug: "friedbasil",
    category: "Dinner",
    ingredients: [
      "Meat of choice (chicken, pork, or shrimp): 200 grams (sliced)",
      "Garlic: 4-5 cloves (minced)",
      "Red chili: 3-4 (sliced, adjust to desired spiciness)",
      "Holy basil leaves: 1 cup",
      "Oyster sauce: 1 tablespoon",
      "Soy sauce: 1 tablespoon",
      "Fish sauce: 1 teaspoon",
      "Sugar: 1 teaspoon",
      "Cooking oil: 2 tablespoons",
      "Water: 2 tablespoons (optional, to adjust consistency)",
    ],
    steps: [
      "Heat cooking oil in a wok or pan over medium heat.",
      "Add minced garlic and chili, stir-fry until fragrant.",
      "Add the meat of choice and stir-fry until it is fully cooked.",
      "Season with oyster sauce, soy sauce, fish sauce, and sugar. Stir well to combine.",
      "Add holy basil leaves and stir quickly. Turn off the heat to preserve the basil's aroma.",
      "If the dish is too dry, add 1-2 tablespoons of water and mix well.",
      "Serve hot with steamed rice, and optionally, a fried egg on top.",
    ],
  },

  {
    id: 31,
    image: "Fried Chicken.png",
    title: "Fried Chicken",
    slug: "Chicken",
    category: "Dinner",
    ingredients: [
      "Chicken Drumsticks: 8 pieces",
      "All-purpose Flour: 2 cups",
      "Cornstarch: 1/4 cup",
      "Salt: 2 teaspoons",
      "Black Pepper: 1 teaspoon",
      "Garlic Powder: 1 teaspoon",
      "Paprika: 1 teaspoon",
      "Cayenne Pepper: 1/2 teaspoon (optional, for spice)",
      "Eggs: 2 (beaten)",
      "Buttermilk: 1 cup",
      "Vegetable Oil: For frying",
    ],
    steps: [
      "Mix buttermilk, eggs, and 1 teaspoon of salt in a large bowl. Add chicken and marinate for at least 2 hours (overnight for best results).",
      "In a separate bowl, combine flour, cornstarch, salt, black pepper, garlic powder, paprika, and cayenne pepper.",
      "Remove chicken from marinade, letting excess drip off. Dredge each piece in the flour mixture until evenly coated.",
      "Heat vegetable oil in a large skillet or deep fryer to 175°C (350°F).",
      "Fry chicken in batches, turning occasionally, for 12-15 minutes or until golden brown and fully cooked (internal temperature of 75°C/165°F).",
      "Remove chicken and place on a wire rack or paper towels to drain excess oil.",
      "Serve hot and enjoy!",
    ],
  },

  {
    id: 32,
    image: "Burrito.png",
    title: "Burrito",
    slug: "Burrito",
    category: "Dinner",
    ingredients: [
      "Large Flour Tortillas: 4",
      "Cooked Rice: 2 cups (white or brown)",
      "Black Beans: 1 cup (cooked or canned, drained and rinsed)",
      "Cooked Chicken, Beef, or Tofu: 2 cups (shredded or diced)",
      "Shredded Cheddar Cheese: 1 cup",
      "Salsa: 1/2 cup",
      "Guacamole: 1/2 cup",
      "Sour Cream: 1/4 cup",
      "Lettuce: 1 cup (shredded)",
      "Tomatoes: 1/2 cup (diced)",
      "Cilantro: Optional (for garnish)",
    ],
    steps: [
      "Warm the tortillas in a dry skillet or microwave for easier folding.",
      "Layer the ingredients in the center of each tortilla: start with rice, followed by black beans, cooked meat (or tofu), shredded cheese, salsa, guacamole, sour cream, lettuce, and tomatoes.",
      "Fold the sides of the tortilla inward, then roll it tightly from the bottom up to form a burrito.",
      "Optional: Place the burrito in a skillet over medium heat for 1-2 minutes per side to crisp up the tortilla.",
      "Serve immediately with extra salsa, guacamole, or sour cream on the side. Enjoy!",
    ],
  },
  //Dinner

  //Dessert
  {
    id: 33,
    image: "Raspberry Macaron.png",
    title: "Raspberry Macaron",
    slug: "RaspberryMacaron",
    category: "Dessert",
    ingredients: [
     "Almond Flour: 120g",
    "Powdered Sugar: 200g",
    "Egg Whites: 3 (room temperature)",
    "Granulated Sugar: 50g",
    "Pink Gel Food Coloring: a few drops",
    "Raspberry Jam: 1/2 cup",
    "Unsalted Butter: 50g (softened, for buttercream)",
    "Powdered Sugar (for buttercream): 100g",
    "Vanilla Extract: 1 teaspoon",
    ],
    steps: [
      "Sift almond flour and powdered sugar.",
    "Whip egg whites until stiff peaks, add sugar, and fold in coloring.",
    "Fold dry ingredients into egg whites until batter flows like lava.",
    "Pipe circles onto a baking sheet, tap to remove air bubbles, and let sit until a skin forms.",
    "Bake at 150°C (300°F) for 15-18 minutes. Cool completely.",
    "Make buttercream by beating butter, powdered sugar, vanilla, and raspberry jam.",
    "Assemble macarons with buttercream filling.",
    "Chill in an airtight container for 24 hours before serving.",
    ],
  },
  
  {
    id: 34,
    image: "Lemon Tart.png",
    title: "Lemon Tart",
    slug: "LemonTart",
    category: "Dessert",
    ingredients: [
      "All-purpose Flour: 1 1/4 cups (for tart crust)",
      "Powdered Sugar: 1/4 cup (for tart crust)",
      "Unsalted Butter: 1/2 cup (cold, for tart crust)",
      "Egg Yolk: 1 (for tart crust)",
      "Cold Water: 2 tablespoons (for tart crust)",
      "Lemons: 3 (zested and juiced, for filling)",
      "Granulated Sugar: 1 cup (for filling)",
      "Eggs: 3 (for filling)",
      "Heavy Cream: 1/2 cup (for filling)",
      "Powdered Sugar: for dusting",
    ],
    steps: [
      "Prepare the crust: Mix flour and powdered sugar. Add cold butter and mix until crumbly. Add egg yolk and cold water, mix until dough forms. Chill for 30 minutes.",
    "Roll out the dough and press into a tart pan. Trim excess dough and prick the base with a fork. Chill for another 15 minutes.",
    "Blind bake the crust: Preheat the oven to 180°C (350°F). Line the crust with parchment paper and fill with pie weights. Bake for 15 minutes, remove weights, and bake for another 10 minutes until golden. Cool completely.",
    "Make the filling: Whisk lemon juice, zest, sugar, eggs, and cream until smooth.",
    "Pour the filling into the cooled crust and bake at 160°C (325°F) for 20-25 minutes, or until the filling is set but slightly wobbly in the center.",
    "Cool to room temperature, then chill in the refrigerator for at least 2 hours.",
    "Dust with powdered sugar before serving.",
    ],
  },

  {
    id: 35,
    image: "Eclair.png",
    title: "Eclair",
    slug: "Eclair",
    category: "Dessert",
    ingredients: [
      "Water: 250 ml (for choux pastry)",
    "Butter: 100 g (cold, for choux pastry)",
    "Salt: 1 tsp (for choux pastry)",
    "Cornstarch: 1 tbsp (for choux pastry)",
    "All-purpose Flour: 150 g (for choux pastry)",
    "Eggs: 4 (for choux pastry)",
    "Heavy Cream: 500 ml (for filling)",
    "Granulated Sugar: 100 g (for filling)",
    "Vanilla Extract: 1 tsp (for filling)",
    "Dark Chocolate: 200 g (for glaze)",
    "Heavy Cream: 100 ml (for glaze)",
    ],
    steps: [
      "Prepare the choux pastry: Boil water, butter, and salt in a pan. Add cornstarch and flour, stir until the mixture thickens and pulls away from the sides. Gradually add eggs one at a time, mixing well after each addition.",
      "Pipe the choux pastry onto a baking sheet in the shape of small logs. Bake in a preheated oven at 180°C (350°F) for 30-35 minutes until golden brown and crisp. Let cool completely.",
      "Make the filling: Whisk the heavy cream and sugar until stiff peaks form. Add vanilla extract and continue to mix until smooth.",
      "Make the chocolate glaze: Melt the dark chocolate and heavy cream together in a bowl, stirring until smooth and glossy.",
      "Assemble the eclairs: Cut the cooled choux pastries in half. Pipe the cream filling into the center of each pastry.",
      "Dip the top of each filled pastry into the chocolate glaze and set aside to cool and set.",
      "Serve and enjoy!",
    ],
  },

  {
    id: 36,
    image: "Chocolate  Souffle.png",
    title: "Chocolate  Souffle",
    slug: "ChocolateSouffle",
    category: "Dessert",
    ingredients: [
      "Dark Chocolate: 200 g",
    "Butter: 3 tbsp",
    "All-purpose Flour: 2 tbsp",
    "Whole Milk: 1/2 cup",
    "Eggs: 4 (separate whites and yolks)",
    "Granulated Sugar: 1/4 cup (for egg whites)",
    "Granulated Sugar: 1/4 cup (for yolks)",
    "Vanilla Extract: 1 tsp",
    "Pinch of Salt",
    "Butter (for greasing ramekins)",
    "Granulated Sugar (for coating ramekins)",
    ],
    steps: [
    "Preheat the oven to 190°C (375°F). Grease 4 ramekins with butter and dust them with sugar, then set aside.",
    "Melt the dark chocolate and butter together in a heatproof bowl over a pot of simmering water (double boiler method). Stir until smooth, then remove from heat and let cool slightly.",
    "In a separate saucepan, combine the flour and milk. Cook over medium heat, whisking constantly until the mixture thickens. Remove from heat and let cool.",
    "In a bowl, whisk the egg yolks with 1/4 cup of granulated sugar until the mixture becomes pale and fluffy. Add the melted chocolate mixture and vanilla extract, and mix well.",
    "In a separate bowl, beat the egg whites with a pinch of salt until soft peaks form. Gradually add the remaining 1/4 cup of granulated sugar and continue beating until stiff peaks form.",
    "Gently fold the egg whites into the chocolate mixture in three additions. Be careful not to deflate the batter.",
    "Spoon the mixture into the prepared ramekins, filling each about 3/4 full.",
    "Bake for 12-15 minutes, or until the soufflés have risen and the tops are set but the center is slightly wobbly.",
    "Serve immediately, dusted with powdered sugar if desired.",
    ],
  },
  //Dessert

  //Drink
  {
    id: 37,
    image: "Strawberry Smoothie.png",
    title: "Strawberry Smoothie",
    slug: "StrawberrySmoothie",
    category: "Drink",
    ingredients: [
      "Strawberries: 200g (fresh or frozen)",
      "Banana: 1 (medium-sized)",
      "Yogurt: 150g (natural or plain)",
      "Milk (or plant-based milk): 100ml",
      "Honey: 1 tablespoon (optional, for sweetness)",
    ],
    steps: [
      "Wash and prepare the strawberries. If using frozen, let them thaw slightly.",
      "Peel the banana and cut it into small pieces.",
      "Add strawberries, banana, yogurt, milk, and honey into a blender.",
      "Blend until smooth and creamy.",
      "Pour into a glass and serve immediately. Add ice for extra refreshment if desired.",
    ],
  },

  {
    id: 38,
    image: "latte.png",
    title: "latte",
    slug: "latte",
    category: "Drink",
    ingredients: [
      "Espresso: 1 shot (about 30ml)",
      "Milk: 200ml",
      "Sugar or Syrup: to taste (optional)",
    ],
    steps: [
      "Brew a shot of espresso using an espresso machine or moka pot.",
      "Heat the milk gently until it's warm (do not boil).",
      "Froth the milk using a frother, steam wand, or by shaking it in a jar and microwaving for a few seconds.",
      "Pour the espresso into a cup.",
      "Slowly pour the frothed milk over the espresso, holding back the foam with a spoon, then spoon the foam on top.",
      "Add sugar or flavored syrup if desired. Serve immediately.",
    ],
  },

  {
    id: 39,
    image: "thaitea.png",
    title: "Thai tea",
    slug: "Thaitea",
    category: "Drink",
    ingredients: [
      "Thai Tea Leaves: 2 tablespoons",
      "Hot Water: 1 cup (240ml)",
      "Sugar: 2 tablespoons (adjust to taste)",
      "Condensed Milk: 2 tablespoons",
      "Evaporated Milk: 2 tablespoons (for topping)",
      "Ice: as needed",
    ],
    steps: [
      "Boil water and pour it over the Thai tea leaves in a teapot or bowl.",
      "Let the tea steep for 5-7 minutes, then strain the tea leaves using a fine sieve or cheesecloth.",
      "While the tea is still hot, stir in sugar and condensed milk until fully dissolved.",
      "Let the tea cool to room temperature, then chill it in the refrigerator if desired.",
      "Fill a glass with ice cubes, pour the tea over the ice, leaving some space at the top.",
      "Drizzle evaporated milk on top for a creamy finish. Serve immediately.",
    ],
  },

  {
    id: 40,
    image: "Chocolate Milkshake.png",
    title: "Chocolate Banana Milkshake",
    slug: "ChocolateMilkshake",
    category: "Drink",
    ingredients: [
      "Banana: 2 (ripe)",
      "Milk (or plant-based milk): 1 1/2 cups",
      "Cocoa Powder: 2 tablespoons",
      "Honey or Maple Syrup: 2 tablespoons",
      "Ice Cubes: 5-6",
    ],
    steps: [
      "Peel the bananas and slice them into chunks.",
    "Add the banana chunks, milk, cocoa powder, honey (or maple syrup), and ice cubes to a blender.",
    "Blend on high speed until the mixture is smooth and creamy.",
    "Taste and adjust sweetness if needed.",
    "Pour the milkshake into a glass and serve immediately.",
    ],
  },
  //Drink
];

export default data;
