
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Navbar from "./components/Navbar";

import SessionProvider from "./components/Provider/session"
import { auth } from "@/config/auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar className="relative z-10" /> {/* Navbar อยู่ข้างหน้า */}
          <div className="relative z-0">{children}</div> {/* เนื้อหาทั้งหมดอยู่ด้านหลัง */}
        </body>
      </SessionProvider>
    </html>
  );
} 
